title: ij start canon printer setup | ij start canon 
description: Setup wireless canon printer with your preferred device using the steps given at Canon.com/ijsetup. Enter canon printer model number and download the software.
